"""
PDF builder — renders the A4 CV HTML template to a single-page PDF via Playwright.

Public API
----------
render_html(cv_data, user_id=...)              -> str    (fully-injected HTML string)
build_pdf(cv_data, output_path, user_id=...)   -> bytes  (raw PDF; also writes file if path given)

Architectural contract
----------------------
Contact information (name, email, phone, linkedin, location) is NEVER
generated by the LLM.  This module injects those values from the hardcoded
_CONTACT dict below.  If a key is missing from _CONTACT it becomes an empty
string — it is never guessed, fabricated, or passed to the model.

cv_data shape (produced by TailorAgent — contact fields are absent by design):
{
  "header":     {"target_title", ...},  # contact fields injected here, never from the LLM
  "summary":    str,
  "experience": [{"role", "company", "dates", "bullets": [str]}],
  "education":  [{"degree", "institution", "dates", "honors", "coursework"}],
  "military_service": {"role_title", "unit_type", "dates", "key_responsibilities"},  # optional, may be None
  "skills":     {"categories": [{"label", "items": [str]}]},
  "languages":  [{"language", "level"}],
  "volunteering": str,
}
"""
from __future__ import annotations

import html as _html
import re
from pathlib import Path


class PdfEngineUnavailable(RuntimeError):
    """
    The headless browser this module renders with is not installed.

    Distinct from a transient render failure on purpose. `pip install
    playwright` provides the Python package but NOT the Chromium binary — that
    needs a separate `playwright install chromium` plus its system libraries,
    which backend/Dockerfile does and a plain pip-based deploy does not. So a
    deployment can import this module, pass every health check, and still be
    permanently incapable of producing a PDF.

    Callers must not present this as retryable: no amount of retrying installs
    a browser. Surfacing it as the same "please try again shortly" error used
    for genuine blips sends users into an infinite retry loop against a wall.
    """


_pdf_engine_available: bool | None = None


async def pdf_engine_available() -> bool:
    """
    Whether Chromium is actually installed, resolved without launching it.

    Answers the exact gap PdfEngineUnavailable's docstring describes: a
    deploy that imports this module fine but can never render a PDF.

    Async because the sync Playwright API raises inside a running asyncio
    loop, which would make this always report "unavailable" from the async
    /health route regardless of the real answer. Cached after the first
    call — a browser binary does not appear or vanish mid-process, and
    /health is probed continuously.
    """
    global _pdf_engine_available
    if _pdf_engine_available is None:
        try:
            from playwright.async_api import async_playwright

            async with async_playwright() as pw:
                _pdf_engine_available = Path(pw.chromium.executable_path).exists()
        except Exception:
            _pdf_engine_available = False
    return _pdf_engine_available


# ── Template resolution ───────────────────────────────────────────────────────
# Legacy default (kept for backward-compat — all existing callers pass no template_id)
TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "templates" / "cv_template.html"

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates" / "cv"

_TEMPLATE_MAP: dict[str, Path] = {
    "t1_classic":    _TEMPLATES_DIR / "t1_classic.html",
    "t2_modern":     _TEMPLATES_DIR / "t2_modern.html",
    "t3_executive":  _TEMPLATES_DIR / "t3_executive.html",
    "t4_minimalist": _TEMPLATES_DIR / "t4_minimalist.html",
    "t5_techmodern": _TEMPLATES_DIR / "t5_techmodern.html",
}

TEMPLATE_REGISTRY: list[dict] = [
    {"id": "t1_classic",    "name": "Classic",             "description": "Traditional serif, black & white"},
    {"id": "t2_modern",     "name": "Modern",               "description": "Serif name, clean sans body, teal accent"},
    {"id": "t3_executive",  "name": "Executive",            "description": "Bold headers, Georgia serif, charcoal"},
    {"id": "t4_minimalist", "name": "Executive Minimalist", "description": "Ultra-clean single column, no color blocks"},
    {"id": "t5_techmodern", "name": "Modern Tech",           "description": "Two-column layout, dark sidebar, teal accent"},
]


def _resolve_template(template_id: str | None) -> Path:
    """Return the Path for the requested template; falls back to the legacy default."""
    if template_id and template_id in _TEMPLATE_MAP:
        p = _TEMPLATE_MAP[template_id]
        if p.exists():
            return p
    return TEMPLATE_PATH

# ── Contact data — sourced exclusively from the caller's own profile, never
# from the LLM ── get_profile(user_id) (user_profile.py) is the single source
# of truth, resolving to the user's actual master_profiles DB row. If a field
# is absent there, it becomes an empty string and the template placeholder is
# blanked — nothing is guessed or hardcoded here.
def _load_contact(user_id: str) -> dict:
    from backend.services.user_profile import get_profile
    p = get_profile(user_id).get("personal", {})
    return {
        "name":     p.get("name",     ""),
        "email":    p.get("email",    ""),
        "phone":    p.get("phone",    ""),
        "linkedin": p.get("linkedin", ""),
        "location": p.get("location", ""),
    }

# Contact field names — strip these from LLM output before injection
_CONTACT_KEYS = frozenset({"name", "email", "phone", "linkedin", "location"})


# ── Low-level helpers ─────────────────────────────────────────────────────────

def _e(text: str) -> str:
    """HTML-escape a plain-text string."""
    return _html.escape(str(text or ""), quote=False)


def _t(text: str, limit: int) -> str:
    """Escape and truncate to limit characters (for short display fields only).
    Never call this on experience bullets — use _e() directly there."""
    return _e(str(text or "")[:limit])


_YEAR_RE    = re.compile(r"(?:19|20)\d{2}")
_PRESENT_RE = re.compile(r"present|current|ongoing|\bnow\b", re.IGNORECASE)


def _format_year_range(raw: str) -> str:
    """Reduce any date-range string to strict 'YYYY - YYYY' (or 'YYYY').

    Source data is inconsistent ("Late 2024 - Early 2025", "2025 - Feb 2026",
    "2023–2026", "03/2019 - 08/2022"). Rather than parsing every textual
    variant, this extracts 4-digit years only and discards everything else
    (months, days, "Late"/"Early", dashes of any kind). An open-ended range
    ("... - Present") keeps the literal "Present" as the end marker instead
    of inventing an end year.
    """
    text = str(raw or "")
    years = _YEAR_RE.findall(text)
    is_open_ended = bool(_PRESENT_RE.search(text))

    if not years:
        return "Present" if is_open_ended else ""

    start = years[0]
    end   = "Present" if is_open_ended else (years[-1] if len(years) > 1 else start)

    return start if start == end else f"{start} - {end}"


def _contact_line(value: str) -> str:
    """Return a full <span class="contact-line"> element, or empty string if blank.

    This ensures absent phone/location fields produce NO DOM node — not an
    empty span that wastes vertical space in the header.
    """
    stripped = str(value or "").strip()
    if not stripped:
        return ""
    return f'<span class="contact-line">{_e(stripped)}</span>'


def _inject(template: str, data: dict) -> str:
    """Replace every {{key}} placeholder; blank out any unreplaced ones."""
    for key, value in data.items():
        template = template.replace(f"{{{{{key}}}}}", str(value) if value is not None else "")
    return re.sub(r"\{\{[^}]+\}\}", "", template)


# ── Section HTML builders ─────────────────────────────────────────────────────

def _build_experience(entries: list[dict]) -> str:
    parts: list[str] = []
    for exp in entries[:5]:
        role    = _t(exp.get("role",    ""), 45)
        company = _t(exp.get("company", ""), 35)
        dates   = _t(_format_year_range(exp.get("dates", "")), 22)
        bullets_html = "".join(
            f"<li>{_e(str(b or ''))}</li>"
            for b in (exp.get("bullets") or [])[:6]
        )
        parts.append(
            f'<div class="exp-entry">'
            f'  <div class="entry-hdr">'
            f'    <div class="entry-meta">'
            f'      <span class="entry-role">{role}</span>'
            f'      <span class="entry-company">{company}</span>'
            f'    </div>'
            f'    <span class="entry-dates">{dates}</span>'
            f'  </div>'
            f'  <ul class="bullets">{bullets_html}</ul>'
            f'</div>'
        )
    return "\n".join(parts)


def _build_education(entries: list[dict]) -> str:
    parts: list[str] = []
    for edu in entries[:3]:
        degree      = _t(edu.get("degree",      ""), 60)
        institution = _t(edu.get("institution", ""), 35)
        dates       = _t(_format_year_range(edu.get("dates", "")), 20)
        honors      = _t(edu.get("honors",      ""), 60)
        coursework  = _t(edu.get("coursework",  ""), 80)

        honors_html     = f'<span class="edu-honors">{honors}</span>' if honors else ""
        coursework_html = (
            f'<span class="edu-coursework">Relevant: {coursework}</span>'
            if coursework else ""
        )

        parts.append(
            f'<div class="edu-entry">'
            f'  <div class="entry-hdr">'
            f'    <div class="entry-meta">'
            f'      <span class="edu-degree">{degree}</span>'
            f'      <span class="edu-institution">{institution}</span>'
            f'    </div>'
            f'    <span class="entry-dates">{dates}</span>'
            f'  </div>'
            f'  {honors_html}{coursework_html}'
            f'</div>'
        )
    return "\n".join(parts)


# JOB-121: must stay >= tailor.py's _SKILLS_CAP (currently 20) — that's where
# skills are actually ranked by JD relevance and selected; a tighter cap here
# would silently re-truncate that careful selection down to whatever
# arbitrary items happen to survive alphabetically/positionally. The A4 page
# this renders onto has a shrink-to-fit safety net (see the <script> block in
# each cv/*.html template) rather than a hard clip, so a generous cap here
# degrades to a slightly smaller page instead of losing content.
_SKILLS_ITEMS_PER_CATEGORY_CAP = 20


def _build_skills(skills_data: dict) -> str:
    """
    Render skills as plain inline text.  Delimiters are written directly into
    the HTML (not via CSS ::after) so they survive PDF rendering and never
    look like interactive web-UI badge components.
    """
    categories = (skills_data or {}).get("categories", [])
    if not categories:
        return ""
    cats_html = []
    for cat in categories[:4]:
        label = _t(cat.get("label", ""), 20)
        items = [_t(s, 25) for s in (cat.get("items") or [])[:_SKILLS_ITEMS_PER_CATEGORY_CAP] if s]
        if not items:
            continue
        # Bullet-separated plain text — no background, no border, no badge look.
        items_text = " · ".join(items)
        cats_html.append(
            f'<div class="skill-cat">'
            f'  <span class="skill-cat-label">{label}</span>'
            f'  <span class="skill-items">{items_text}</span>'
            f'</div>'
        )
    if not cats_html:
        return ""
    return (
        f'<div class="side-sec">'
        f'  <h2 class="sec-title">Skills</h2>'
        + "".join(cats_html) +
        f'</div>'
    )


def _build_languages(languages: list[dict]) -> str:
    """
    Render each language's name and level as two separate spans — no literal
    separator between them.  Some templates lay lang-name/lang-level side by
    side with a gap, others split them to opposite ends of the row
    (justify-content: space-between); a hardcoded "— " prefix only reads
    correctly in the first layout, so it's left to each template's own CSS.
    """
    if not languages:
        return ""
    rows = []
    for lang in languages[:5]:
        name  = _t(lang.get("language", ""), 20)
        level = _t(lang.get("level",    ""), 35)
        if not name:
            continue
        level_html = f'<span class="lang-level">{level}</span>' if level else ""
        rows.append(
            f'<div class="lang-row">'
            f'  <span class="lang-name">{name}</span>'
            f'  {level_html}'
            f'</div>'
        )
    if not rows:
        return ""
    return (
        f'<div class="side-sec">'
        f'  <h2 class="sec-title">Languages</h2>'
        f'  {"".join(rows)}'
        f'</div>'
    )


def _build_military(mil: dict | None) -> str:
    """
    Render the military-service block, or nothing at all.

    Reads the canonical CVDataSchema names (role_title/unit_type). A missing or
    None section produces an empty string rather than a bare heading — absent
    must mean absent, since a "Military Service" title with nothing under it is
    worse than omitting the section for a candidate who did not serve.

    key_responsibilities is optional and usually empty: it earns page space only
    for candidates whose service IS the leadership evidence (a recent graduate),
    which is why the <ul> is omitted entirely when the list is empty rather than
    rendered as an empty container that still costs vertical rhythm.
    """
    if not mil or not mil.get("role_title"):
        return ""
    role  = _t(mil.get("role_title", ""), 45)
    unit  = _t(mil.get("unit_type",  ""), 60)   # canonical unit strings run to ~41 chars
    dates = _t(_format_year_range(mil.get("dates", "")), 20)
    # unit is optional — omit the span entirely so ::before separators (used by
    # some templates) don't leave a dangling "—" when there's no unit text.
    unit_html = f'<span class="mil-unit">{unit}</span>' if unit else ""

    responsibilities = [str(r).strip() for r in (mil.get("key_responsibilities") or []) if str(r).strip()]
    resp_html = (
        f'<ul class="bullets">{"".join(f"<li>{_e(r)}</li>" for r in responsibilities[:3])}</ul>'
        if responsibilities else ""
    )

    return (
        f'<div class="side-sec">'
        f'  <h2 class="sec-title">Military Service</h2>'
        f'  <div class="entry-hdr">'
        f'    <div class="entry-meta">'
        f'      <span class="mil-role">{role}</span>'
        f'      {unit_html}'
        f'    </div>'
        f'    <span class="entry-dates">{dates}</span>'
        f'  </div>'
        f'  {resp_html}'
        f'</div>'
    )


def _build_volunteering(text: str) -> str:
    if not text:
        return ""
    return (
        f'<div class="side-sec">'
        f'  <h2 class="sec-title">Volunteering</h2>'
        f'  <div class="vol-text">{_t(text, 120)}</div>'
        f'</div>'
    )


# ── Public API ────────────────────────────────────────────────────────────────

def _flatten(cv_data: dict, user_id: str) -> dict:
    """Map TailorAgent JSON output to the flat placeholder dict the template needs.

    Contact fields come exclusively from the caller's own profile (get_profile
    (user_id)).  Any contact-like keys in cv_data are silently dropped here so
    the LLM can never override them.
    """
    # Normalise first: a CV can reach the renderer straight from storage
    # (GET /cached/{job_id}, a re-render of an old tailored_cv) without having
    # passed through the tailor pipeline, and those documents may still carry
    # the pre-unification `title`/`military` keys. Converting here means the
    # builders below read canonical names only, and an old CV keeps rendering
    # exactly as it did instead of silently losing its title and service block.
    from backend.models.cv import normalize_cv
    cv_data = normalize_cv(cv_data, context="pdf_builder")

    # Strip any contact fields the LLM may have accidentally included
    clean = {k: v for k, v in cv_data.items() if k not in _CONTACT_KEYS}

    flat: dict = {}

    # ── Contact — always from the caller's own profile, never from LLM ──────
    # name, email, linkedin → plain escaped strings (always rendered inside a
    #   static <span> in the template).
    # phone, location       → full <span> element or empty string; the template
    #   injects them raw so that a missing value leaves NO DOM node at all.
    contact = _load_contact(user_id)
    flat["name"]          = _e(contact.get("name",     ""))
    flat["email"]         = _e(contact.get("email",    ""))
    flat["linkedin"]      = _e(contact.get("linkedin", ""))
    flat["phone_line"]    = _contact_line(contact.get("phone",    ""))
    flat["location_line"] = _contact_line(contact.get("location", ""))

    # ── LLM-generated content ─────────────────────────────────────────────────
    flat["title"]   = _t((clean.get("header") or {}).get("target_title", ""), 58)
    flat["summary"] = _t(clean.get("summary", ""), 400)

    flat["experience_blocks"]    = _build_experience(clean.get("experience", []))
    flat["education_blocks"]     = _build_education(clean.get("education",  []))
    flat["skills_section"]       = _build_skills(clean.get("skills", {}))
    flat["languages_section"]    = _build_languages(clean.get("languages", []))
    flat["military_section"]     = _build_military(clean.get("military_service"))
    flat["volunteering_section"] = _build_volunteering(clean.get("volunteering", ""))

    return flat


def render_html(cv_data: dict, template_id: str | None = None, *, user_id: str) -> str:
    """Return the fully-rendered HTML string for the CV.

    user_id selects whose contact data (name/email/phone/linkedin/location)
    gets injected — defaults to "default" (the legacy single-user scaffold)
    for backward compatibility with any caller that hasn't been updated to
    pass the real caller's user_id.
    """
    template = _resolve_template(template_id).read_text(encoding="utf-8")
    return _inject(template, _flatten(cv_data, user_id))


async def build_pdf(cv_data: dict, output_path: str | Path | None = None,
                    template_id: str | None = None, *, user_id: str) -> bytes:
    """
    Render cv_data to a single-page A4 PDF using Playwright headless Chromium.

    Returns raw PDF bytes. If output_path is provided, also writes the file.
    """
    from playwright.async_api import async_playwright

    html_str = render_html(cv_data, template_id=template_id, user_id=user_id)

    async with async_playwright() as pw:
        try:
            browser = await pw.chromium.launch()
        except Exception as exc:
            # Matched on the message rather than the exception class:
            # playwright._impl._errors.Error is a private path, and the same
            # class covers ordinary launch failures too. The wording below is
            # what Playwright prints when the binary is absent.
            msg = str(exc).lower()
            if "executable doesn't exist" in msg or "playwright install" in msg:
                raise PdfEngineUnavailable(
                    "Chromium is not installed in this environment — PDF rendering "
                    "is unavailable. Deploy via backend/Dockerfile (which runs "
                    "`playwright install --with-deps chromium`), or run that command "
                    "with system dependencies available."
                ) from exc
            raise
        page    = await browser.new_page()
        await page.set_content(html_str, wait_until="networkidle")
        pdf_bytes = await page.pdf(
            format="A4",
            print_background=True,
            prefer_css_page_size=True,
            # tagged=True writes real PDF structure tags (headings, lists,
            # reading order) derived from the HTML's own semantic markup —
            # required for SI 5568 Part 2 (accessible digital documents) and
            # for any screen reader to make sense of the exported CV at all.
            # outline=True builds the PDF's bookmark tree from the same <h1>-
            # <h6> hierarchy. Both need Playwright >= 1.42 (pinned: 1.49.1)
            # and both depend on the templates using real heading tags rather
            # than styled <div>/<span> — see templates/cv/*.html.
            tagged=True,
            outline=True,
        )
        await browser.close()

    if output_path is not None:
        Path(output_path).write_bytes(pdf_bytes)

    return pdf_bytes
