"""create linkedin schema and jobs table

Revision ID: f5bd530a002f
Revises: 
Create Date: 2026-07-23 14:22:00.375643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5bd530a002f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate doesn't detect schema creation — added by hand.
    op.execute("CREATE SCHEMA IF NOT EXISTS linkedin")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('linkedin_job_id', sa.String(), nullable=True),
    sa.Column('job_url_normalized', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('posted_text', sa.String(), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('company_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exact_posted_text', sa.String(), nullable=True),
    sa.Column('applicants_text', sa.String(), nullable=True),
    sa.Column('seniority_level', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('job_function', sa.String(), nullable=True),
    sa.Column('industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_logo_url', sa.Text(), nullable=True),
    sa.Column('linkedin_status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('insertion_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='linkedin'
    )
    op.create_index('ix_linkedin_jobs_company', 'jobs', ['company'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_insertion_time', 'jobs', ['insertion_time'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_is_active', 'jobs', ['is_active'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_job_url', 'jobs', ['job_url'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_job_url_normalized_unique', 'jobs', ['job_url_normalized'], unique=True, schema='linkedin')
    op.create_index('ix_linkedin_jobs_last_seen_at', 'jobs', ['last_seen_at'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_linkedin_job_id_unique', 'jobs', ['linkedin_job_id'], unique=True, schema='linkedin', postgresql_where=sa.text('linkedin_job_id IS NOT NULL'))
    op.create_index('ix_linkedin_jobs_linkedin_status', 'jobs', ['linkedin_status'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_location', 'jobs', ['location'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_scraped_at', 'jobs', ['scraped_at'], unique=False, schema='linkedin')
    op.create_index('ix_linkedin_jobs_updated_at', 'jobs', ['updated_at'], unique=False, schema='linkedin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_linkedin_jobs_updated_at', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_scraped_at', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_location', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_linkedin_status', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_linkedin_job_id_unique', table_name='jobs', schema='linkedin', postgresql_where=sa.text('linkedin_job_id IS NOT NULL'))
    op.drop_index('ix_linkedin_jobs_last_seen_at', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_job_url_normalized_unique', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_job_url', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_is_active', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_insertion_time', table_name='jobs', schema='linkedin')
    op.drop_index('ix_linkedin_jobs_company', table_name='jobs', schema='linkedin')
    op.drop_table('jobs', schema='linkedin')
    # ### end Alembic commands ###

    # Deliberately NOT dropping the `linkedin` schema here — schema-level
    # drop is a much bigger blast radius than this one table's downgrade
    # should have (e.g. if another future table were added to the same
    # schema). Drop it manually if the schema itself really needs removing.
