"""
One-time (re-runnable) cleanup: deletes test-artifact rows from
master_profiles whose user_id matches the synthetic prefixes generated by
backend/tests/test_proficiency_update.py's TestUpdateSkillsHandlerUpdateAction
suite ("handler-compose-<uuid>", "handler-update-<uuid>", "handler-missing-<uuid>").

Root cause (fixed separately, see that test file's _patch_engine fixture):
_handle_update_skills() calls _refresh_baseline(), which reached
backend.core.database.ENGINE via a fresh inline import at call time rather
than the test's in-memory engine — writing a real master_profiles row for
every synthetic test user_id. Confirmed via row-count diff (see
docs/db-redesign-proposal.md) that ONLY master_profiles was affected — no
other table shows any handler-* rows.

This script only ever targets rows matching those exact prefixes. It never
touches any other user_id, including the two pre-existing
"handler-compose-3ab34c3c-..."/"handler-update-4f8008f1-..." rows that were
already on Dev Supabase before this session's data migration — those match
the same prefix and are included here on purpose, per explicit instruction
to remove all handler-compose-*/handler-update-* rows now that their origin
is fully confirmed as test pollution, not unexplained legacy data.

Network/write safety gate (mirrors migrate_jobs_db_to_supabase.py): no row is
ever deleted from Postgres unless BOTH
  1. --allow-write is passed on the command line, AND
  2. ALLOW_MASTER_PROFILES_CLEANUP=true is set in the environment
are true. Omitting --allow-write always runs the safe, read-only preview
path instead — reports matching row counts, makes no writes.

The local SQLite file (backend/jobs.db) is cleaned unconditionally when
--sqlite is passed (no network risk, a local file, and the whole point of
this cleanup) — but only together with --allow-write.

Usage
-----
    # Safe default — read-only preview, no writes anywhere:
    python -m backend.scripts.cleanup_test_master_profiles

    # Real cleanup, Postgres only:
    ALLOW_MASTER_PROFILES_CLEANUP=true python -m backend.scripts.cleanup_test_master_profiles --allow-write

    # Real cleanup, Postgres + local SQLite:
    ALLOW_MASTER_PROFILES_CLEANUP=true python -m backend.scripts.cleanup_test_master_profiles --allow-write --sqlite
"""
from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from sqlalchemy import text  # noqa: E402

from backend.core.postgres import get_pg_session  # noqa: E402

_SQLITE_PATH = _PROJECT_ROOT / "backend" / "jobs.db"

_TEST_PREFIXES = ("handler-compose-", "handler-update-", "handler-missing-")

_WHERE_CLAUSE = " OR ".join(f"user_id LIKE '{p}%'" for p in _TEST_PREFIXES)


def _guard_write(args: argparse.Namespace) -> None:
    env_allowed = os.environ.get("ALLOW_MASTER_PROFILES_CLEANUP", "").strip().lower() in ("1", "true", "yes")
    cli_allowed = bool(getattr(args, "allow_write", False))
    if not (cli_allowed and env_allowed):
        print(
            "[GUARD] Refusing to delete: requires BOTH --allow-write AND "
            "ALLOW_MASTER_PROFILES_CLEANUP=true in the environment. Omit "
            "--allow-write to run the safe read-only preview instead.",
            file=sys.stderr,
        )
        sys.exit(1)


def _postgres_matching_count() -> int:
    with get_pg_session() as session:
        return session.execute(text(f"SELECT count(*) FROM public.master_profiles WHERE {_WHERE_CLAUSE}")).scalar_one()


def _sqlite_matching_count() -> int:
    conn = sqlite3.connect(str(_SQLITE_PATH))
    try:
        return conn.execute(f"SELECT count(*) FROM master_profiles WHERE {_WHERE_CLAUSE}").fetchone()[0]
    finally:
        conn.close()


def run_preview() -> None:
    pg_count = _postgres_matching_count()
    print(f"[preview] Dev Supabase master_profiles: {pg_count} row(s) match a test prefix — would be deleted.")
    if _SQLITE_PATH.exists():
        sq_count = _sqlite_matching_count()
        print(f"[preview] {_SQLITE_PATH}: {sq_count} row(s) match a test prefix — would be deleted with --sqlite.")
    print("[preview] Run with --allow-write (+ ALLOW_MASTER_PROFILES_CLEANUP=true) to actually delete.")


def run_cleanup(clean_sqlite: bool) -> None:
    with get_pg_session() as session:
        before = _postgres_matching_count()
        result = session.execute(text(f"DELETE FROM public.master_profiles WHERE {_WHERE_CLAUSE}"))
        session.commit()
        print(f"[postgres] Deleted {result.rowcount} row(s) (expected {before}).")

    if clean_sqlite and _SQLITE_PATH.exists():
        conn = sqlite3.connect(str(_SQLITE_PATH))
        try:
            before_sq = _sqlite_matching_count()
            cur = conn.execute(f"DELETE FROM master_profiles WHERE {_WHERE_CLAUSE}")
            conn.commit()
            print(f"[sqlite] Deleted {cur.rowcount} row(s) (expected {before_sq}).")
        finally:
            conn.close()


def main():
    parser = argparse.ArgumentParser(description="Delete test-artifact rows from master_profiles.")
    parser.add_argument("--allow-write", action="store_true",
                         help="Required (together with ALLOW_MASTER_PROFILES_CLEANUP=true) to actually delete. "
                              "Omit this flag to run the safe read-only preview instead (default).")
    parser.add_argument("--sqlite", action="store_true",
                         help="Also clean the local backend/jobs.db file (only applies with --allow-write).")
    args = parser.parse_args()

    if not args.allow_write:
        run_preview()
        return

    _guard_write(args)
    run_cleanup(clean_sqlite=args.sqlite)


if __name__ == "__main__":
    main()
