import { LegalPage } from '@/components/legal/LegalPage'

export const metadata = { title: 'Terms of Service — JobApply' }

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="August 2026">
      <h2>What JobApply does</h2>
      <p>
        JobApply helps you apply to jobs. You give it your work history and a target role or job
        posting; it produces a tailored CV, a fit score against the job, and tools to track and
        follow up on applications (a Kanban-style board, AI-drafted outreach messages, and an
        AI assistant that can answer questions about your profile or a job).
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You need an account to use JobApply, created via email/password or Google sign-in.</li>
        <li>You&apos;re responsible for keeping your credentials secure and for what happens under your account.</li>
        <li>You must be accurate about your own work history — the product exists to help you
          apply for real jobs, and a fabricated CV is a risk to you, not to us.</li>
      </ul>

      <h2>AI-generated content</h2>
      <ul>
        <li>Tailored CVs, fit scores, outreach messages, and chat replies are generated by AI
          models — currently Anthropic Claude, and Google where that provider is enabled —
          based on the information you provide.</li>
        <li>AI output can be wrong. Review every document before you send it to an employer —
          you are the one submitting it, and you&apos;re responsible for its accuracy.</li>
        <li>JobApply applies automated checks intended to keep generated content grounded in
          what you told it, but these checks are not perfect and do not guarantee every claim in
          a generated document is accurate.</li>
      </ul>

      <h2>Acceptable use</h2>
      <p>Don&apos;t use JobApply to:</p>
      <ul>
        <li>Submit knowingly false information about yourself to an employer.</li>
        <li>Attempt to disrupt, overload, or gain unauthorized access to the service.</li>
        <li>Scrape, resell, or redistribute job data or AI output at scale outside normal personal use.</li>
      </ul>

      <h2>Job and company data</h2>
      <p>
        JobApply aggregates job postings from public job boards and other sources. We don&apos;t
        control the accuracy of that data, and a listing appearing in your feed isn&apos;t a
        guarantee it&apos;s still open or accurately described by the source.
      </p>

      <h2>No warranty</h2>
      <p>
        JobApply is provided as-is. We don&apos;t guarantee you&apos;ll get interviews or offers,
        that the service will be uninterrupted, or that AI-generated content will be error-free.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms as the product changes. Material changes will be reflected here
        with an updated date.
      </p>

      <h2>Contact</h2>
      <p>Questions about these terms: <a href="mailto:support@jobapply.ai">support@jobapply.ai</a>.</p>
    </LegalPage>
  )
}
