"""
ORM model for `public.all_jobs` — the canonical, cross-provider jobs table.

Schema created by backend/alembic_app_schema/versions/
9f25d77ed964_create_all_jobs_table.py (hand-authored DDL, not autogenerated
from this model — the migration came first; this model exists so
backend/repositories/all_jobs_repository.py has a typed `Table` to query
against). Lives on the same shared Postgres engine as `linkedin.jobs`
(backend/core/postgres.py) — default `public` schema, no schema= needed.

Read side: GET /api/all-jobs (backend/api/routes/all_jobs.py). Write side:
backend/repositories/all_jobs_repository.py's bulk_upsert_all_jobs() (a
Core-level `INSERT ... ON CONFLICT DO UPDATE`, not an ORM write through this
model) — called directly by backend/scripts/linkedin_israel_jobs.py for a
live scrape (no CSV involved), and by backend/scripts/
upsert_linkedin_csv_to_all_jobs.py for manual CSV backfills.
"""
from __future__ import annotations

import uuid

from sqlalchemy import Boolean, Column, DateTime, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID

from backend.core.postgres import LinkedInBase


class AllJobRow(LinkedInBase):
    __tablename__ = "all_jobs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    source = Column(String, nullable=False, default="linkedin")
    source_job_id = Column(Text, nullable=True)
    canonical_job_key = Column(Text, nullable=False)

    first_seen_at = Column(DateTime(timezone=True), nullable=False)
    last_seen_at = Column(DateTime(timezone=True), nullable=False)
    insertion_time = Column(DateTime(timezone=True), nullable=False)
    updated_at = Column(DateTime(timezone=True), nullable=False)
    last_scraped_at = Column(DateTime(timezone=True), nullable=True)
    is_active = Column(Boolean, nullable=True)
    closed_at = Column(DateTime(timezone=True), nullable=True)
    raw_payload = Column(JSONB, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False)

    job_title = Column(Text, nullable=True)
    company_name = Column(Text, nullable=True)
    company_url = Column(Text, nullable=True)
    company_logo_url = Column(Text, nullable=True)
    job_url = Column(Text, nullable=False)
    normalized_job_url = Column(Text, nullable=False)
    location = Column(Text, nullable=True)
    seniority_level = Column(Text, nullable=True)
    employment_type = Column(Text, nullable=True)
    job_function = Column(Text, nullable=True)
    industries = Column(ARRAY(Text), nullable=True)
    description = Column(Text, nullable=True)
    posted_text = Column(Text, nullable=True)
    exact_posted_text = Column(Text, nullable=True)
    applicants_text = Column(Text, nullable=True)
