import { describe, expect, it } from 'vitest'
import { applyCvPatch, jsonEqual, parsePointer } from './cvPatch'
import type { RFC6902PatchOp } from './apiTypes'

// ── Contract fixtures ───────────────────────────────────────────────────────
// Every patch in `CONTRACT_CASES` is verbatim output from
// `jsonpatch.JsonPatch.from_diff()` at version 1.33 — the version pinned in
// backend/requirements.txt and the exact call backing `diff_cv()`
// (backend/services/cv_patch_service.py). They were generated by diffing the
// CV below against the stated edit, and each was round-tripped through the
// Python applier before being pasted here, so `expected` is what the server
// itself lands on. These are the cases that make this a contract test rather
// than a test of my reading of the RFC: if the backend's differ ever emits a
// shape this applier does not handle, one of these fails.

const BASE_CV = {
  header: {
    full_name: 'R M', target_title: 'Product Manager',
    email: '', phone: '', location: '', linkedin: '',
  },
  summary: 'CS lead moving into product.',
  experience: [
    {
      role: 'CS Manager', company: 'GO-OUT', dates: '2021-2024',
      bullets: ['Ran onboarding for 40 accounts.', 'Cut churn 12%.', 'Built the QBR deck.'],
    },
    {
      role: 'Support Lead', company: 'River', dates: '2019-2021',
      bullets: ['Handled tier-2 escalations.'],
    },
  ],
  education: [{ degree: 'BA', institution: 'TAU', dates: '2019', honors: '', coursework: '' }],
  military_service: {
    role_title: 'Squad Commander', unit_type: 'Infantry', dates: '2015-2018',
    key_responsibilities: ['Led 12 soldiers.'],
  },
  skills: {
    categories: [
      { label: 'Product', items: ['Roadmapping', 'Discovery'] },
      { label: 'Tools', items: ['Jira'] },
    ],
  },
  languages: [{ language: 'Hebrew', level: 'Native' }],
  volunteering: '',
}

/** Structured-clone the frozen base so each case starts from a pristine doc. */
const base = () => JSON.parse(JSON.stringify(BASE_CV)) as typeof BASE_CV

type ContractCase = {
  name:     string
  patch:    RFC6902PatchOp[]
  /** Applied to a fresh copy of BASE_CV to build the expected document. */
  expect:   (cv: ReturnType<typeof base>) => void
}

const CONTRACT_CASES: ContractCase[] = [
  {
    name:  'rewrite one bullet → replace',
    patch: [{ op: 'replace', path: '/experience/0/bullets/1', value: 'Cut churn 12% across a 40-account book.' }],
    expect: cv => { cv.experience[0].bullets[1] = 'Cut churn 12% across a 40-account book.' },
  },
  {
    name:  'append a skill → add at end index',
    patch: [{ op: 'add', path: '/skills/categories/1/items/1', value: 'Salesforce' }],
    expect: cv => { cv.skills.categories[1].items.push('Salesforce') },
  },
  {
    name:  'delete a bullet → remove',
    patch: [{ op: 'remove', path: '/experience/0/bullets/2' }],
    expect: cv => { cv.experience[0].bullets.splice(2, 1) },
  },
  {
    // The case the handoff's "add/remove/replace only" note missed: the
    // differ's optimizer collapses a remove+add pair into a move.
    name:  'swap two bullets → move',
    patch: [{ op: 'move', from: '/experience/0/bullets/0', path: '/experience/0/bullets/1' }],
    expect: cv => {
      const b = cv.experience[0].bullets
      ;[b[0], b[1]] = [b[1], b[0]]
    },
  },
  {
    name:  'retitle → replace inside header',
    patch: [{ op: 'replace', path: '/header/target_title', value: 'Senior Product Manager' }],
    expect: cv => { cv.header.target_title = 'Senior Product Manager' },
  },
  {
    name:  'add a military responsibility → add into nested array',
    patch: [{ op: 'add', path: '/military_service/key_responsibilities/1', value: 'Owned live-fire training.' }],
    expect: cv => { cv.military_service.key_responsibilities.push('Owned live-fire training.') },
  },
  {
    name:  'drop military service → replace with null',
    patch: [{ op: 'replace', path: '/military_service', value: null }],
    expect: cv => { (cv as { military_service: unknown }).military_service = null },
  },
  {
    name:  'edits across three sections',
    patch: [
      { op: 'replace', path: '/experience/0/bullets/0', value: 'Owned onboarding for 40 enterprise accounts.' },
      { op: 'replace', path: '/summary', value: 'Product manager with a CS foundation.' },
      { op: 'add', path: '/skills/categories/0/items/2', value: 'A/B testing' },
    ],
    expect: cv => {
      cv.experience[0].bullets[0] = 'Owned onboarding for 40 enterprise accounts.'
      cv.summary = 'Product manager with a CS foundation.'
      cv.skills.categories[0].items.push('A/B testing')
    },
  },
  {
    // The nastiest real shape the differ produces: prepending a role rewrites
    // every scalar in place and shuffles bullets BETWEEN experience entries
    // with a run of moves whose indices only resolve correctly if each move
    // removes before it inserts.
    name:  'prepend a new role → 12-op replace/remove/move/add sequence',
    patch: [
      { op: 'replace', path: '/experience/0/dates',   value: '2024-' },
      { op: 'replace', path: '/experience/0/company', value: 'New' },
      { op: 'replace', path: '/experience/0/role',    value: 'PM' },
      { op: 'add',     path: '/experience/0/bullets/0', value: 'Shipped v1.' },
      { op: 'replace', path: '/experience/1/dates',   value: '2021-2024' },
      { op: 'replace', path: '/experience/1/company', value: 'GO-OUT' },
      { op: 'replace', path: '/experience/1/role',    value: 'CS Manager' },
      { op: 'remove',  path: '/experience/1/bullets/0' },
      { op: 'move', from: '/experience/0/bullets/1', path: '/experience/1/bullets/0' },
      { op: 'move', from: '/experience/0/bullets/1', path: '/experience/1/bullets/1' },
      { op: 'move', from: '/experience/0/bullets/1', path: '/experience/1/bullets/2' },
      { op: 'add', path: '/experience/2', value: { role: 'Support Lead', company: 'River', dates: '2019-2021', bullets: ['Handled tier-2 escalations.'] } },
    ],
    expect: cv => {
      cv.experience.unshift({ role: 'PM', company: 'New', dates: '2024-', bullets: ['Shipped v1.'] })
    },
  },
]

describe('applyCvPatch — backend contract (jsonpatch 1.33 from_diff output)', () => {
  for (const c of CONTRACT_CASES) {
    it(c.name, () => {
      const expected = base()
      c.expect(expected)

      const result = applyCvPatch(base(), c.patch)

      expect(result.ok).toBe(true)
      if (!result.ok) return
      expect(result.doc).toEqual(expected)
      expect(result.opsApplied).toBe(c.patch.length)
    })
  }
})

describe('applyCvPatch — immutability', () => {
  it('never mutates the input document', () => {
    const doc  = base()
    const snap = JSON.stringify(doc)
    applyCvPatch(doc, [{ op: 'replace', path: '/summary', value: 'changed' }])
    expect(JSON.stringify(doc)).toBe(snap)
  })

  it('does not alias values carried in the patch', () => {
    const op: RFC6902PatchOp = { op: 'add', path: '/skills/categories/0/items/0', value: 'X' }
    const result = applyCvPatch(base(), [{ op: 'replace', path: '/languages', value: [{ language: 'English', level: 'Fluent' }] }, op])
    expect(result.ok).toBe(true)
    if (!result.ok) return
    // Mutating the applied document must not reach back into the patch.
    ;(result.doc.languages[0] as { level: string }).level = 'Native'
    expect(result.doc.languages[0].level).toBe('Native')
  })

  it('returns the original document object when the patch is empty', () => {
    const doc = base()
    const result = applyCvPatch(doc, [])
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.doc).toBe(doc)
    expect(result.opsApplied).toBe(0)
  })

  it('treats a null/undefined patch as a no-op success', () => {
    const doc = base()
    expect(applyCvPatch(doc, null)).toMatchObject({ ok: true, opsApplied: 0 })
    expect(applyCvPatch(doc, undefined)).toMatchObject({ ok: true, opsApplied: 0 })
  })
})

describe('applyCvPatch — all-or-nothing failure', () => {
  it('returns the ORIGINAL document when a later op fails', () => {
    const doc = base()
    const result = applyCvPatch(doc, [
      { op: 'replace', path: '/summary', value: 'this one is fine' },
      { op: 'replace', path: '/experience/9/role', value: 'never applied' },
    ])
    expect(result.ok).toBe(false)
    if (result.ok) return
    expect(result.kind).toBe('path_not_found')
    // Not the half-applied document — the untouched one.
    expect(result.doc).toBe(doc)
    expect(result.doc.summary).toBe('CS lead moving into product.')
  })

  it('reports which operation failed', () => {
    const result = applyCvPatch(base(), [
      { op: 'replace', path: '/summary', value: 'ok' },
      { op: 'remove', path: '/nope' },
    ])
    expect(result.ok).toBe(false)
    if (result.ok) return
    expect(result.error).toContain('operation 1')
    expect(result.error).toContain('remove /nope')
  })

  it.each<[string, RFC6902PatchOp]>([
    ['unknown op',            { op: 'frobnicate' as RFC6902PatchOp['op'], path: '/summary', value: 1 }],
    ['path without a slash',  { op: 'replace', path: 'summary', value: 1 }],
    ['add without a value',   { op: 'add', path: '/summary' }],
    ['move without a from',   { op: 'move', path: '/summary' }],
    ['leading-zero index',    { op: 'replace', path: '/experience/01/role', value: 'x' }],
    ['non-numeric index',     { op: 'replace', path: '/experience/first/role', value: 'x' }],
  ])('rejects %s as malformed', (_label, op) => {
    const result = applyCvPatch(base(), [op])
    expect(result.ok).toBe(false)
    if (result.ok) return
    expect(result.kind).toBe('malformed')
  })

  it('rejects a non-array patch', () => {
    const result = applyCvPatch(base(), { op: 'replace' } as unknown as RFC6902PatchOp[])
    expect(result).toMatchObject({ ok: false, kind: 'malformed' })
  })
})

describe('applyCvPatch — RFC 6902 semantics', () => {
  it('add inserts into an array rather than overwriting', () => {
    const result = applyCvPatch({ items: ['a', 'c'] }, [{ op: 'add', path: '/items/1', value: 'b' }])
    expect(result.ok && result.doc.items).toEqual(['a', 'b', 'c'])
  })

  it('add accepts the "-" append token', () => {
    const result = applyCvPatch({ items: ['a'] }, [{ op: 'add', path: '/items/-', value: 'b' }])
    expect(result.ok && result.doc.items).toEqual(['a', 'b'])
  })

  it('add may target one past the end but no further', () => {
    expect(applyCvPatch({ items: ['a'] }, [{ op: 'add', path: '/items/1', value: 'b' }]).ok).toBe(true)
    expect(applyCvPatch({ items: ['a'] }, [{ op: 'add', path: '/items/2', value: 'b' }]).ok).toBe(false)
  })

  it('replace requires an existing target, unlike add', () => {
    expect(applyCvPatch({ a: 1 }, [{ op: 'add', path: '/b', value: 2 }]).ok).toBe(true)
    expect(applyCvPatch({ a: 1 }, [{ op: 'replace', path: '/b', value: 2 }]).ok).toBe(false)
    expect(applyCvPatch({ items: ['a'] }, [{ op: 'replace', path: '/items/1', value: 'b' }]).ok).toBe(false)
  })

  it('add can write a key whose value is explicitly null', () => {
    const result = applyCvPatch({ military_service: null }, [
      { op: 'replace', path: '/military_service', value: { role_title: 'Squad Commander' } },
    ])
    expect(result.ok && result.doc.military_service).toEqual({ role_title: 'Squad Commander' })
  })

  it('remove deletes an object key and closes an array gap', () => {
    expect(applyCvPatch({ a: 1, b: 2 }, [{ op: 'remove', path: '/a' }]).ok).toBe(true)
    const arr = applyCvPatch({ items: ['a', 'b', 'c'] }, [{ op: 'remove', path: '/items/1' }])
    expect(arr.ok && arr.doc.items).toEqual(['a', 'c'])
  })

  it('remove refuses the whole document', () => {
    expect(applyCvPatch({ a: 1 }, [{ op: 'remove', path: '' }])).toMatchObject({ ok: false, kind: 'malformed' })
  })

  it('move removes before it inserts', () => {
    // ['a','b','c','d'] -> remove index 3 -> ['a','b','c'] -> insert 'd' at 0.
    const result = applyCvPatch({ items: ['a', 'b', 'c', 'd'] }, [{ op: 'move', from: '/items/3', path: '/items/0' }])
    expect(result.ok && result.doc.items).toEqual(['d', 'a', 'b', 'c'])
  })

  it('move between containers detaches from the source', () => {
    const result = applyCvPatch(
      { x: ['one'], y: [] as string[] },
      [{ op: 'move', from: '/x/0', path: '/y/0' }],
    )
    expect(result.ok && result.doc).toEqual({ x: [], y: ['one'] })
  })

  it('move onto itself is a legal no-op', () => {
    const result = applyCvPatch({ items: ['a', 'b'] }, [{ op: 'move', from: '/items/0', path: '/items/0' }])
    expect(result.ok && result.doc.items).toEqual(['a', 'b'])
  })

  it('move into its own child is refused', () => {
    const result = applyCvPatch({ a: { b: 1 } }, [{ op: 'move', from: '/a', path: '/a/b' }])
    expect(result).toMatchObject({ ok: false, kind: 'malformed' })
  })

  it('copy leaves the source in place and deep-clones the value', () => {
    const result = applyCvPatch(
      { src: [{ n: 1 }], dst: [] as unknown[] },
      [{ op: 'copy', from: '/src/0', path: '/dst/0' }],
    )
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.doc.src).toEqual([{ n: 1 }])
    ;(result.doc.dst[0] as { n: number }).n = 99
    expect(result.doc.src[0].n).toBe(1)
  })

  it('test passes on a structural match and fails otherwise', () => {
    const doc = { experience: [{ bullets: ['Cut churn 12%.'] }] }
    expect(applyCvPatch(doc, [{ op: 'test', path: '/experience/0/bullets/0', value: 'Cut churn 12%.' }]).ok).toBe(true)
    const stale = applyCvPatch(doc, [{ op: 'test', path: '/experience/0/bullets/0', value: 'something else' }])
    expect(stale).toMatchObject({ ok: false, kind: 'test_failed' })
  })

  it('a failing test aborts the ops that follow it', () => {
    const doc = { summary: 'original' }
    const result = applyCvPatch(doc, [
      { op: 'test', path: '/summary', value: 'stale expectation' },
      { op: 'replace', path: '/summary', value: 'never applied' },
    ])
    expect(result.ok).toBe(false)
    if (result.ok) return
    expect(result.doc.summary).toBe('original')
  })

  it('replaces the whole document through the empty pointer', () => {
    const result = applyCvPatch({ a: 1 }, [{ op: 'replace', path: '', value: { b: 2 } }])
    expect(result.ok && result.doc).toEqual({ b: 2 })
  })
})

describe('parsePointer', () => {
  it('returns [] for the whole-document pointer', () => {
    expect(parsePointer('')).toEqual([])
  })

  it('rejects a pointer that does not start with /', () => {
    expect(parsePointer('experience/0')).toBeNull()
  })

  it('unescapes ~1 before ~0, per RFC 6901', () => {
    // "~01" encodes the literal "~1" — decoding ~0 first would yield "/".
    expect(parsePointer('/~01')).toEqual(['~1'])
    expect(parsePointer('/a~1b')).toEqual(['a/b'])
    expect(parsePointer('/a~0b')).toEqual(['a~b'])
  })

  it('addresses a key containing a slash', () => {
    const result = applyCvPatch({ 'a/b': 1 }, [{ op: 'replace', path: '/a~1b', value: 2 }])
    expect(result.ok && result.doc).toEqual({ 'a/b': 2 })
  })

  it('keeps empty tokens, which address the "" key', () => {
    expect(parsePointer('/')).toEqual([''])
  })
})

describe('jsonEqual', () => {
  it('compares nested structures by value', () => {
    expect(jsonEqual({ a: [1, { b: 2 }] }, { a: [1, { b: 2 }] })).toBe(true)
    expect(jsonEqual({ a: [1, { b: 2 }] }, { a: [1, { b: 3 }] })).toBe(false)
  })

  it('is key-order independent but key-set sensitive', () => {
    expect(jsonEqual({ a: 1, b: 2 }, { b: 2, a: 1 })).toBe(true)
    expect(jsonEqual({ a: 1 }, { a: 1, b: undefined })).toBe(false)
  })

  it('does not conflate an array with an object', () => {
    expect(jsonEqual([], {})).toBe(false)
    expect(jsonEqual(['a'], { 0: 'a' })).toBe(false)
  })

  it('distinguishes null from missing and from falsy scalars', () => {
    expect(jsonEqual(null, null)).toBe(true)
    expect(jsonEqual(null, undefined)).toBe(false)
    expect(jsonEqual(0, '')).toBe(false)
    expect(jsonEqual(0, false)).toBe(false)
  })
})
